CREATE VIEW [EXT].[WKEAPRODUCTEXTENDEDVIEW] AS
(
    SELECT
       alt.ITEMID,
	   alt.PRODUCT,
	   t.ITEMID as MTITEMID,
	   t.PRODUCT as MTPRODUCT,
	   t.DATAAREAID
    FROM [ax].INVENTTABLE AS alt
	JOIN [ax].INVENTTABLE as t on alt.ITEMID = t.ALTITEMID and alt.DATAAREAID = t.DATAAREAID
)
GO
